# html lang
language: en

menuname: Luna's Blog

# Your Name
author: Luna

# main menu navigation
menu:
  AboutğŸ‘€: /about
  HomeğŸƒ: http://tanger.cloud/
  GitHubğŸ§¨: https://github.com/redhat123456

topmenu:
  Main: /
  about: /about

## ì›¹ ì„¤ëª…
description: 

## ì‚¬ì´íŠ¸í‚¤ì›Œë“œ: ì˜ì–´ ì‰¼í‘œë¡œ êµ¬ë¶„
keywords: hexo,theme,MiHoYo

## blog í”„ë¡œí•„ì‚¬ì§„
img_src: https://KuraiLuna.github.io/images/lumine.png

# Title
logo_title: Luna's Developer Diary

# Your Slogan
words: printf("Hello World!");

# ìœ„ìª½ í…Œë‘ë¦¬ ìŠ¬ë¼ì´ë“œ
# topmenu:
# í™ˆ index:/
# about: /about ì •ë³´

# stylesheets loaded in the <head>
stylesheets:
  - /css/MiHoYo.css

# scripts loaded in the end of the body
scripts:
  - /js/MiHoYo.js

# ë¦¬ë·° ì‹œìŠ¤í…œ | Comments
## ë„ë©”ì¸ ì œí•œì„ í–ˆìŠµë‹ˆë‹¤, ìì‹ ì˜ KEYë¡œ ë³€ê²½í•´ ì£¼ì„¸ìš”.
## valineì„ ë„ë©´ enableì„ falseë¡œ ì„¤ì •í•©ë‹ˆë‹¤
valine:
  enable: false
  appId:
  appKey:
